title: Luis Sevillano | Visual Storytelling & Geospatial Developer
email: luissevillanopires@gmail.com
description:
  I design and develop static and interactive visual narratives. My work focuses on bringing clarity to complex data through the lens of cartography and remote sensing, exploring the intersection of geography and journalism
author_name: Luis Sevillano
logo_url: "https://avatars0.githubusercontent.com/u/11034169?v=4"
logo: "https://avatars0.githubusercontent.com/u/11034169?v=4"
url: "https://luissevillano.net"
enforce_ssl: luissevillano.net
baseurl: ""
permalink: "/:title"
timezone: "Europe/Madrid /:title"
mathjax: true
repo: "https://github.com/luissevillano/luissevillano.github.io"
twitter_username: sepirdata
github_username: luissevillano
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
sass:
  style: ":compressed"
include:
  - robots.txt
exclude:
  - LICENSE
  - README.md
  - CNAME
  - vendor
  - Gemfile
  - script
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: "null"
  - scope:
      type: pages
    values:
      layout: page
  - scope:
      type: posts
    values:
      layout: post
collections:
  tags:
    output: true
    permalink: "/tags/:title/"
